name: PDF to Word Converter

on:
  push:
    paths:
      - "input/**.pdf"   # Trigger only when new PDFs are pushed into input/

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run conversion script
        run: |
          mkdir -p input output
          python convert.py

      - name: Upload converted DOCX files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: converted-docx
          path: output/*.docx
