name: PDF to Word Converter

on:
  push:
    paths:
      - "input/**.pdf"

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run conversion script
        run: python convert.py

      - name: Commit converted files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add output/
          git commit -m "Auto-converted PDFs to DOCX" || echo "No changes to commit"
          git push
